language: node_js
sudo: false
node_js:
  - 0.12
  - 4

addons:
  apt:
    packages:
    - mono-complete

cache:
   directories:
     - node_modules
     - bower_components
   - apt  
#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y mono-complete

before_script:

after_success:
#  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
#  - cat ./coverage/lcov.info | codeclimate
#  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < ./coverage/**/lcov.info